removes access files overview permission
localgovdrupal/localgov_core pull request #221
Opened 2024-05-23 13:40 UTC by markconroy

Closes #220 

Removes the permission to access the files overview permission. It's probably only developers that need this for debugging things, so we can add that manually when needed, or add it to the admin role (when we have one).

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

2024-05-23 15:15 UTC, andybroomfield commented on modules/localgov_roles/localgov_roles.install
> +}
I'm not so sure of this, if there are custom roles that have been assigned this then they will get deleted. Sometimes it is useful if there are files which for what ever reason are not yet in media. I'd limit this to localgov drupal provided roles, and I'd check if they have been altered from default. Noting the update hook also runs this.

2024-05-28 10:50 UTC, stephen-cox commented
As @andybroomfield points out - there are potential issues removing this permission for existing sites. Maybe just remove the update hook. We could always add a release note suggesting existing sites do this manually if it's important.

2024-05-28 11:50 UTC, finnlewis commented
Just discussing in Merge Tuesday.

Generally happy to remove the permission for fresh installs.

However, deploying an update hook that removes permissions from existing roles is perhaps a bit too far.

Perhaps we should remove the permission in the default install, and add instructions for people to clarify that they can remove the permission for certain roles.

2024-05-28 11:54 UTC, finnlewis commented
Note: would like to check where the permission 'access files overview' is being set to see if we can remove it there rather than here.

2024-08-02 11:10 UTC, stephen-cox reviewed
There's been some discussion on #220 on how desirable this actually is. At least one person finds the files list useful, but it's also needed to ensure a file has been deleted.

If we go ahead and merge this we need to at least document how to get it back should it be needed.

2024-08-05 15:01 UTC, markconroy commented
Maybe we could have the best of both worlds.

1. Remove the files menu link from the admin/content page
2. Add the files menu link to the tabs on the admin/content/media page

That would mean people can still get to the files tab, but don't mistake if for the media tab which is what they usually want. It might make more sense to go to "Admin > Content > Media > Files" for content editors, as then it looks like files are a sub-item of media items (which they are).

2024-08-06 11:23 UTC, ekes commented
MT: moving the link sounds more promising than removing permission; 
maybe check with @willguv or product group about moving it being good.

Are there files being used that aren't in media?

2024-08-13 09:57 UTC, finnlewis commented
Note: @willguv is away for a few weeks, so might want to park this until he's back.

2024-08-27 11:37 UTC, finnlewis commented
@willguv likes the sound of @markconroy's suggestion!

2024-09-02 13:09 UTC, markconroy commented
I've rewritten this PR. New version:

1. Adds the `views.view.files.yml` view to our `config/install` so new sites can use it.
2. Adds a local task for the Files tab to sit under 'Media' on the `/admin/content/*` pages
3. Adds an update hook to update current sites to move 'Files' from admin/content/files to admin/content/media/files

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

2024-09-04 13:26 UTC, stephen-cox requested changes
I have tested this and it works, I do have a couple of comments though.

2024-09-04 13:26 UTC, stephen-cox commented on localgov_core.install
I don't think we should be moving the files tab for existing installs. The new location isn't very obvious and will be confusing to people who are using files already.

2024-09-04 13:26 UTC, stephen-cox commented on modules/localgov_media/config/install/views.view.files.yml
This should be in the optional directory rather than install.

2024-09-04 14:19 UTC, markconroy commented on localgov_core.install
I've removed the update hook now, however given that we are creating a `localgov_core.links.task.yml` file, we will now have a 'Files' tab on the admin/content page and also on the `admin/content/media` page. 

Maybe that's okay, and existing sites can update the view manually if they want to remove the tab from the `admin/content` page.

2024-09-10 10:52 UTC, stephen-cox commented on localgov_core.install
There is a little oddity here for existing installs as going to the files listing now looks like this 

![image](https://github.com/user-attachments/assets/29f51f52-b39d-471f-a4bc-315459cdab83)

Let's discuss as a Merge Tuesday as to how much if an issue it is.

I also note that Files appears under Content in the menu and where perhaps it should under Content > Media. But if this is a problem then it could be another issue.

2024-09-10 11:33 UTC, finnlewis commented
@willguv we're discussing this in Merge Tuesday and not sure of the motivation for moving the files tab.

Could we discuss with content and product people? 

Files and media entities are different things, and there are use cases for accessing both. 

We could perhaps address this with a how-to or other documentation?

2024-09-25 13:42 UTC, markconroy commented
@finnlewis Will stated at product group meeting today that we should just create an update hook to remove the tab from admin/content and write a release note to say where the files tab has been moved to.

https://github.com/localgovdrupal/localgov_core/issues/220#issuecomment-2374125908

2024-10-15 11:26 UTC, merged

2025-05-13 09:43 UTC, ekes commented
referencing #283 follow-up for why this is done, and potentially reviewing how this is done.